// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateInvoiceResponse post create invoice response
//
// swagger:model postCreateInvoiceResponse
type PostCreateInvoiceResponse struct {

	// invoice id
	// Example: 7503cd8a-c921-4368-a32d-6c1d01d86da9
	// Required: true
	// Format: uuid4
	InvoiceID *strfmt.UUID4 `json:"invoice_id"`

	// 跳转到支付页面
	// Example: https://xxx.com
	// Required: true
	JumpURL *string `json:"jump_url"`
}

// Validate validates this post create invoice response
func (m *PostCreateInvoiceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvoiceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJumpURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateInvoiceResponse) validateInvoiceID(formats strfmt.Registry) error {

	if err := validate.Required("invoice_id", "body", m.InvoiceID); err != nil {
		return err
	}

	if err := validate.FormatOf("invoice_id", "body", "uuid4", m.InvoiceID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateInvoiceResponse) validateJumpURL(formats strfmt.Registry) error {

	if err := validate.Required("jump_url", "body", m.JumpURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create invoice response based on context it is used
func (m *PostCreateInvoiceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateInvoiceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateInvoiceResponse) UnmarshalBinary(b []byte) error {
	var res PostCreateInvoiceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
