swagger: "2.0"
info:
  title: github.com/trino-network/pay-srv
  version: 0.1.0

paths:
  /api/v1/invoices/create:
    post:
      security:
        - Bearer: []
      description: |-
        支付前调用，创建票据
      tags:
        - invoices
      summary: create invoice
      operationId: PostCreateInvoice
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: ../definitions/invoice.yml#/definitions/PostCreateInvoicePayload
      responses:
        "200":
          description: PostCreateInvoiceResponse
          schema:
            $ref: ../definitions/invoice.yml#/definitions/PostCreateInvoiceResponse
        400:
          $ref: "../paths/auth.yml#/responses/ValidationError"
        401:
          $ref: "../paths/auth.yml#/responses/AuthUnauthorizedResponse"
        403:
          description: "PublicHTTPError"
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
            
  /api/v1/invoices/{id}:
    get:
      security:
        - Bearer: [ ]
      description: |-
        收到回调通知后调用，获取收据信息
      tags:
        - invoices
      summary: get invoice
      operationId: GetInvoice
      parameters:
        - name: id
          in: path
          type: string
          description: id of invoice
          required: true
      responses:
        "200":
          description: GetInvoiceResponse
          schema:
            $ref: ../definitions/invoice.yml#/definitions/GetInvoiceResponse
        400:
          $ref: "../paths/auth.yml#/responses/ValidationError"
        401:
          $ref: "../paths/auth.yml#/responses/AuthUnauthorizedResponse"
        403:
          description: "PublicHTTPError"
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  /api/v1/invoices/payment/{id}:
    get:
      description: |-
        支付页面获取支付信息
      tags:
        - invoices
      summary: get invoice payment info
      operationId: GetInvoicePaymentInfo
      parameters:
        - name: id
          in: path
          type: string
          description: id of invoice
          required: true
      responses:
        "200":
          description: GetInvoicePaymentInfoResponse
          schema:
            $ref: ../definitions/invoice.yml#/definitions/GetInvoicePaymentInfoResponse

